In [24]:
# import our modules
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.feature_selection import SelectKBest, chi2, f_classif, SelectFromModel
from sklearn.ensemble import RandomForestClassifier

In [31]:
# displaying all columns in the dataset
pd.set_option('display.max_columns', None)

#reading and displaying the dataset in pandas
data = pd.read_csv('Attrition.csv', low_memory=False)

# Sample and display 5 rows of our dataset
data.sample(5)

,id,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
38,39,36,No,Travel_Rarely,852,Research & Development,5,4,Life Sciences,1,51,2,Female,82,2,1,Research Scientist,1,Married,3419,13072,9,Y,Yes,14,3,4,80,1,6,3,4,1,1,0,0
1351,1352,48,No,Travel_Frequently,117,Research & Development,22,3,Medical,1,1900,4,Female,58,3,4,Manager,4,Divorced,17174,2437,3,Y,No,11,3,2,80,1,24,3,3,22,17,4,7
1103,1104,48,No,Travel_Rarely,492,Sales,16,4,Life Sciences,1,1557,3,Female,96,3,2,Sales Executive,3,Divorced,6439,13693,8,Y,No,14,3,3,80,1,18,2,3,8,7,7,7
1339,1340,22,Yes,Travel_Rarely,391,Research & Development,7,1,Life Sciences,1,1878,4,Male,75,3,1,Research Scientist,2,Single,2472,26092,1,Y,Yes,23,4,1,80,0,1,2,3,1,0,0,0
436,437,33,Yes,Travel_Rarely,587,Research & Development,10,1,Medical,1,584,1,Male,38,1,1,Laboratory Technician,4,Divorced,3408,6705,7,Y,No,13,3,1,80,3,8,2,3,4,3,1,3

# Converting categorical range to binary

# We have to convert our age range to binary, in other to avoid errors when working on our model

In [32]:
# we make use of the map function to reassign the data in the column
data['Attrition'] = data.Attrition.map({'Yes' : 1,
                                    'No': 0})

# Sample and display 5 rows after the transformation
data.Attrition.sample(5)

309     0
27      0
204     1
1288    0
212     0
Name: Attrition, dtype: int64

In [33]:
# we make use of the map function to reassign the data in the column
data['OverTime'] = data.OverTime.map({'Yes' : 1,
                                    'No': 0})

# Sample and display 5 rows after the transformation
data.OverTime.sample(5)

1370    0
1209    0
550     0
319     1
109     0
Name: OverTime, dtype: int64

In [34]:
data.drop(columns=['id', 'EmployeeCount', 'EmployeeNumber'], inplace=True, axis=1)
data.sample(5)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1404,42,0,Non-Travel,335,Research & Development,23,2,Life Sciences,4,Male,37,2,2,Research Scientist,3,Single,4332,14811,1,Y,0,12,3,4,80,0,20,2,3,20,9,3,7
67,45,0,Travel_Rarely,1339,Research & Development,7,3,Life Sciences,2,Male,59,3,3,Research Scientist,1,Divorced,9724,18787,2,Y,0,17,3,3,80,1,25,2,3,1,0,0,0
1353,34,1,Non-Travel,967,Research & Development,16,4,Technical Degree,4,Male,85,1,1,Research Scientist,1,Married,2307,14460,1,Y,1,23,4,2,80,1,5,2,3,5,2,3,0
1443,42,0,Travel_Rarely,300,Research & Development,2,3,Life Sciences,1,Male,56,3,5,Manager,3,Married,18880,17312,5,Y,0,11,3,1,80,0,24,2,2,22,6,4,14
1238,23,0,Travel_Rarely,160,Research & Development,4,1,Medical,3,Female,51,3,1,Laboratory Technician,2,Single,3295,12862,1,Y,0,13,3,3,80,0,3,3,1,3,2,1,2

In [35]:
data.describe()

,Age,Attrition,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,MonthlyRate,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,0.161224,802.485714,9.192517,2.912925,2.721769,65.891156,2.729932,2.063946,2.728571,6502.931293,14313.103401,2.693197,0.282993,15.209524,3.153741,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,0.367863,403.509100,8.106864,1.024165,1.093082,20.329428,0.711561,1.106940,1.102846,4707.956783,7117.786044,2.498009,0.450606,3.659938,0.360824,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,0.000000,102.000000,1.000000,1.000000,1.000000,30.000000,1.000000,1.000000,1.000000,1009.000000,2094.000000,0.000000,0.000000,11.000000,3.000000,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,0.000000,465.000000,2.000000,2.000000,2.000000,48.000000,2.000000,1.000000,2.000000,2911.000000,8047.000000,1.000000,0.000000,12.000000,3.000000,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,0.000000,802.000000,7.000000,3.000000,3.000000,66.000000,3.000000,2.000000,3.000000,4919.000000,14235.500000,2.000000,0.000000,14.000000,3.000000,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,0.000000,1157.000000,14.000000,4.000000,4.000000,83.750000,3.000000,3.000000,4.000000,8379.000000,20461.500000,4.000000,1.000000,18.000000,3.000000,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1.000000,1499.000000,29.000000,5.000000,4.000000,100.000000,4.000000,5.000000,4.000000,19999.000000,26999.000000,9.000000,1.000000,25.000000,4.000000,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [38]:
data.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'Over18',
       'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [42]:
columns = ['Age', 'Attrition', 'DailyRate',
       'DistanceFromHome', 'Education',
       'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobSatisfaction',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager']
data[columns].sample(5)

,Age,Attrition,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,MonthlyRate,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
312,31,0,192,2,4,3,32,3,1,4,2695,7747,0,1,18,3,2,80,1,3,2,1,2,2,2,2
1343,29,0,592,7,3,4,59,3,1,1,2062,19384,3,0,14,3,2,80,0,11,2,3,3,2,1,2
605,38,0,471,12,3,1,45,2,2,1,6288,4284,2,0,15,3,3,80,1,13,3,2,4,3,1,2
79,46,0,945,5,2,2,80,3,2,2,5021,10425,8,1,22,4,4,80,1,16,2,3,4,2,0,2
835,35,0,528,8,4,3,100,3,1,3,4323,7108,1,0,17,3,2,80,0,6,2,1,5,4,1,4

In [43]:
# Print the correlation matrix
data[columns].corr()

,Age,Attrition,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,MonthlyRate,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
Age,1.000000,-0.159205,0.010661,-0.001686,0.208034,0.010146,0.024287,0.029820,0.509604,-0.004892,0.497855,0.028051,0.299635,0.028062,0.003634,0.001904,0.053535,NaN,0.037510,0.680381,-0.019621,-0.021490,0.311309,0.212901,0.216513,0.202089
Attrition,-0.159205,1.000000,-0.056652,0.077924,-0.031373,-0.103369,-0.006846,-0.130016,-0.169105,-0.103481,-0.159840,0.015170,0.043494,0.246118,-0.013478,0.002889,-0.045872,NaN,-0.137145,-0.171063,-0.059478,-0.063939,-0.134392,-0.160545,-0.033019,-0.156199
DailyRate,0.010661,-0.056652,1.000000,-0.004985,-0.016806,0.018355,0.023381,0.046135,0.002966,0.030571,0.007707,-0.032182,0.038153,0.009135,0.022704,0.000473,0.007846,NaN,0.042143,0.014515,0.002453,-0.037848,-0.034055,0.009932,-0.033229,-0.026363
DistanceFromHome,-0.001686,0.077924,-0.004985,1.000000,0.021042,-0.016075,0.031131,0.008783,0.005303,-0.003669,-0.017014,0.027473,-0.029251,0.025514,0.040235,0.027110,0.006557,NaN,0.044872,0.004628,-0.036942,-0.026556,0.009508,0.018845,0.010029,0.014406
Education,0.208034,-0.031373,-0.016806,0.021042,1.000000,-0.027128,0.016775,0.042438,0.101589,-0.011296,0.094961,-0.026084,0.126317,-0.020322,-0.011111,-0.024539,-0.009118,NaN,0.018422,0.148280,-0.025100,0.009819,0.069114,0.060236,0.054254,0.069065
EnvironmentSatisfaction,0.010146,-0.103369,0.018355,-0.016075,-0.027128,1.000000,-0.049857,-0.008278,0.001212,-0.006784,-0.006259,0.037600,0.012594,0.070132,-0.031701,-0.029548,0.007665,NaN,0.003432,-0.002693,-0.019359,0.027627,0.001458,0.018007,0.016194,-0.004999
HourlyRate,0.024287,-0.006846,0.023381,0.031131,0.016775,-0.049857,1.000000,0.042861,-0.027853,-0.071335,-0.015794,-0.015297,0.022157,-0.007782,-0.009062,-0.002172,0.001330,NaN,0.050263,-0.002334,-0.008548,-0.004607,-0.019582,-0.024106,-0.026716,-0.020123
JobInvolvement,0.029820,-0.130016,0.046135,0.008783,0.042438,-0.008278,0.042861,1.000000,-0.012630,-0.021476,-0.015271,-0.016322,0.015012,-0.003507,-0.017205,-0.029071,0.034297,NaN,0.021523,-0.005533,-0.015338,-0.014617,-0.021355,0.008717,-0.024184,0.025976
JobLevel,0.509604,-0.169105,0.002966,0.005303,0.101589,0.001212,-0.027853,-0.012630,1.000000,-0.001944,0.950300,0.039563,0.142501,0.000544,-0.034730,-0.021222,0.021642,NaN,0.013984,0.782208,-0.018191,0.037818,0.534739,0.389447,0.353885,0.375281
JobSatisfaction,-0.004892,-0.103481,0.030571,-0.003669,-0.011296,-0.006784,-0.071335,-0.021476,-0.001944,1.000000,-0.007157,0.000644,-0.055699,0.024539,0.020002,0.002297,-0.012454,NaN,0.010690,-0.020185,-0.005779,-0.019459,-0.003803,-0.002305,-0.018214,-0.027656
MonthlyIncome,0.497855,-0.159840,0.007707,-0.017014,0.094961,-0.006259,-0.015794,-0.015271,0.950300,-0.007157,1.000000,0.034814,0.149515,0.006089,-0.027269,-0.017120,0.025873,NaN,0.005408,0.772893,-0.021736,0.030683,0.514285,0.363818,0.344978,0.344079
MonthlyRate,0.028051,0.015170,-0.032182,0.027473,-0.026084,0.037600,-0.015297,-0.016322,0.039563,0.000644,0.034814,1.000000,0.017521,0.021431,-0.006429,-0.009811,-0.004085,NaN,-0.034323,0.026442,0.001467,0.007963,-0.023655,-0.012815,0.001567,-0.036746
NumCompaniesWorked,0.299635,0.043494,0.038153,-0.029251,0.126317,0.012594,0.022157,0.015012,0.142501,-0.055699,0.149515,0.017521,1.000000,-0.020786,-0.010238,-0.014095,0.052733,NaN,0.030075,0.237639,-0.066054,-0.008366,-0.118421,-0.090754,-0.036814,-0.110319
OverTime,0.028062,0.246118,0.009135,0.025514,-0.020322,0.070132,-0.007782,-0.003507,0.000544,0.024539,0.006089,0.021431,-0.020786,1.000000,-0.005433,0.004369,0.048493,NaN,-0.000449,0.012754,-0.079113,-0.027092,-0.011687,-0.029758,-0.012239,-0.041586
PercentSalaryHike,0.003634,-0.013478,0.022704,0.040235,-0.011111,-0.031701,-0.009062,-0.017205,-0.034730,0.020002,-0.027269,-0.006429,-0.010238,-0.005433,1.000000,0.773550,-0.040490,NaN,0.007528,-0.020608,-0.005221,-0.003280,-0.035991,-0.001520,-0.022154,-0.011985
PerformanceRating,0.001904,0.002889,0.000473,0.027110,-0.024539,-0.029548,-0.002172,-0.029071,-0.021222,0.002297,-0.017120,-0.009811,-0.014095,0.004369,0.773550,1.000000,-0.031351,NaN,0.003506,0.006744,-0.015579,0.002572,0.003435,0.034986,0.017896,0.022827
RelationshipSatisfaction,0.053535,-0.045872,0.007846,0.006557,-0.009118,0.007665,0.001330,0.034297,0.021642,-0.012454,0.025873,-0.004085,0.052733,0.048493,-0.040490,-0.031351,1.000000,NaN,-0.045952,0.024054,0.002497,0.019604,0.019367,-0.015123,0.033493,-0.000867
StandardHours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
StockOptionLevel,0.037510,-0.137145,0.042143,0.044872,0.018422,0.003432,0.050263,0.021523,0.013984,0.010690,0.005408,-0.034323,0.030075,-0.000449,0.007528,0.003506,-0.045952,NaN,1.000000,0.010136,0.011274,0.004129,0.015058,0.050818,0.014352,0.024698
TotalWorkingYears,0.680381,-0.171063,0.014515,0.004628,0.148280,-0.002693,-0.002334,-0.005533,0.782208,-0.020185,0.772893,0.026442,0.237639,0.012754,-0.020608,0.006744,0.024054,NaN,0.010136,1.000000,-0.035662,0.001008,0.628133,0.460365,0.404858,0.459188
TrainingTimesLastYear,-0.019621,-0.059478,0.002453,-0.036942,-0.025100,-0.019359,-0.008548,-0.015338,-0.018191,-0.005779,-0.021736,0.001467,-0.066054,-0.079113,-0.005221,-0.015579,0.002497,NaN,0.011274,-0.035662,1.000000,0.028072,0.003569,-0.005738,-0.002067,-0.004096
WorkLifeBalance,-0.021490,-0.063939,-0.037848,-0.026556,0.009819,0.027627,-0.004607,-0.014617,0.037818,-0.019459,0.030683,0.007963,-0.008366,-0.027092,-0.003280,0.002572,0.019604,NaN,0.004129,0.001008,0.028072,1.000000,0.012089,0.049856,0.008941,0.002759
YearsAtCompany,0.311309,-0.134392,-0.034055,0.009508,0.069114,0.001458,-0.019582,-0.021355,0.534739,-0.003803,0.514285,-0.023655,-0.118421,-0.011687,-0.035991,0.003435,0.019367,NaN,0.015058,0.628133,0.003569,0.012089,1.000000,0.758754,0.618409,0.769212
YearsInCurrentRole,0.212901,-0.160545,0.009932,0.018845,0.060236,0.018007,-0.024106,0.008717,0.389447,-0.002305,0.363818,-0.012815,-0.090754,-0.029758,-0.001520,0.034986,-0.015123,NaN,0.050818,0.460365,-0.005738,0.049856,0.758754,1.000000,0.548056,0.714365
YearsSinceLastPromotion,0.216513,-0.033019,-0.033229,0.010029,0.054254,0.016194,-0.026716,-0.024184,0.353885,-0.018214,0.344978,0.001567,-0.036814,-0.012239,-0.022154,0.017896,0.033493,NaN,0.014352,0.404858,-0.002067,0.008941,0.618409,0.548056,1.000000,0.510224
YearsWithCurrManager,0.202089,-0.156199,-0.026363,0.014406,0.069065,-0.004999,-0.020123,0.025976,0.375281,-0.027656,0.344079,-0.036746,-0.110319,-0.041586,-0.011985,0.022827,-0.000867,NaN,0.024698,0.459188,-0.004096,0.002759,0.769212,0.714365,0.510224,1.000000

In [48]:
df = data[columns]
# Separate features (X) and target variable (y)
X = df.drop('Attrition', axis=1)
y = df['Attrition']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [62]:
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

c:\Users\PC\Desktop\HR_attrition\hr\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [63]:
lr_predictions = lr.predict(X_test)
print("Logistic Regression Accuracy:", lr_predictions)

Logistic Regression Accuracy: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]

In [67]:
lr_accuracy = accuracy_score(lr_predictions, y_test)
print("Logistic Regression Accuracy:", lr_accuracy)

Logistic Regression Accuracy: 0.8707482993197279

In [49]:
# Method 1: Correlation Analysis
correlation_matrix = df.corr()
correlation_with_target = correlation_matrix['Attrition'].abs().sort_values(ascending=False)
selected_features_corr = correlation_with_target[1:].index.tolist()  # Select top 5 correlated features
print("Selected features using correlation analysis:", selected_features_corr)

Selected features using correlation analysis: ['OverTime', 'TotalWorkingYears', 'JobLevel', 'YearsInCurrentRole', 'MonthlyIncome', 'Age', 'YearsWithCurrManager', 'StockOptionLevel', 'YearsAtCompany', 'JobInvolvement', 'JobSatisfaction', 'EnvironmentSatisfaction', 'DistanceFromHome', 'WorkLifeBalance', 'TrainingTimesLastYear', 'DailyRate', 'RelationshipSatisfaction', 'NumCompaniesWorked', 'YearsSinceLastPromotion', 'Education', 'MonthlyRate', 'PercentSalaryHike', 'HourlyRate', 'PerformanceRating', 'StandardHours']

In [61]:
# Method 2: Feature Importance with Random Forest
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
feature_importances = pd.Series(rf.feature_importances_, index=X.columns).sort_values(ascending=False)
selected_features_rf = feature_importances[1:].index.tolist()  # Select top 5 important features
print("Selected features using feature importance (Random Forest):", selected_features_rf)

Selected features using feature importance (Random Forest): ['OverTime', 'DailyRate', 'Age', 'MonthlyRate', 'TotalWorkingYears', 'HourlyRate', 'DistanceFromHome', 'YearsAtCompany', 'PercentSalaryHike', 'StockOptionLevel', 'NumCompaniesWorked', 'YearsWithCurrManager', 'YearsSinceLastPromotion', 'JobSatisfaction', 'EnvironmentSatisfaction', 'TrainingTimesLastYear', 'JobInvolvement', 'RelationshipSatisfaction', 'YearsInCurrentRole', 'WorkLifeBalance', 'JobLevel', 'Education', 'PerformanceRating', 'StandardHours']

In [60]:
sfm_selector = SelectFromModel(rf, threshold='median')
X_train_sfm = sfm_selector.fit_transform(X_train, y_train)
X_test_sfm = sfm_selector.transform(X_test)